### ISSUE TITLE
A valid MAC address could not be obtained. - Ubuntu 19.10

### ISSUE THREAD

**Issue by droopanu** [thebigmunch/google-music#15]
Hi,

**I just updated my install to ubuntu 19.10 (from 19.04) and I get the following error:**

[2020-01-30 16:47:53] Logging in to Music Manager
Traceback (most recent call last):
  File "/usr/local/bin/gms", line 10, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/dist-packages/google_music_scripts/cli.py", line 618, in run
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/google_music_scripts/commands.py", line 374, in do_upload
    mm = google_music.musicmanager(args.username, uploader_id=args.uploader_id)
  File "/usr/local/lib/python3.7/dist-packages/google_music/api.py", line 105, in musicmanager
    token_handler_kwargs=None
  File "/usr/local/lib/python3.7/dist-packages/google_music/clients/musicmanager.py", line 79, in __init__
    raise OSError("A valid MAC address could not be obtained.")
OSError: A valid MAC address could not be obtained.

**This is the result of get_mac():**

root@streamripper:~# python3
Python 3.7.5 (default, Nov 20 2019, 09:21:52)
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from uuid import getnode as get_mac
>>> get_mac()
102388028459550
>>>
root@streamripper:~# python3
Python 3.7.5 (default, Nov 20 2019, 09:21:52)
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from uuid import getnode as get_mac
>>> get_mac()
102388028459550
>>> q

**And my network config:**

root@streamripper:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
108: eth0@if109: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether c6:68:e1:63:96:82 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.86.30/24 brd 192.168.86.255 scope global dynamic eth0
       valid_lft 85077sec preferred_lft 85077sec

**Comment by thebigmunch** [comment]
If you are in a VM/PaaS environment, then it's likely that a hardware address couldn't be obtained. When ``getnode`` can't obtain a hardware address, it returns a random address with a certain bit set. If we used that, a new device would be registered on Google Music every login. And Google Music only allows up to 10 devices.

If not, there have been some reports of this in the past with gmusicapi. Debugging was done, but nothing was really able to be determined from it. Unfortunately, nothing can really be done in the code for this as its just interpreting what is given to it by Python/the system. You can instead pass an uploader ID in the CLI. So, for ``c6:68:e1:63:96:82`` as found in your network config, google-music would turn that into ``C6:68:E1:63:96:82-username`` if a username is given or just ``C6:68:E1:63:96:82`` if not. And, google-music-scripts allows you to set this in the config file so you wouldn't need to pass it every time.

**Comment by droopanu** [comment]
hmm .. interesting ....
I am in a virtual environment (lxc container), but it worked in ubuntu 19.04.
I guess something broke in the updated python version.
That result of get_mac() is not random. I'm getting the same value each time. So I have a feeling the encoding is changed somehow...

How can I configure the mac address to be used by google-music-scripts?
I'm using gms script from cli

Cheers,
Liviu
