### ISSUE TITLE
Token cannot be saved

### ISSUE THREAD

**Issue by fdw** [thebigmunch/google-music#5]
Unfortunately, I have a new problem with the latest release: The script cannot save the OAuth token. Instead of creating the directory `~/.local/share/google-music` and a file `musicmanager.token` in it, it also creates the directory `musicmanager.token` and thus cannot save it as a json file.

```
Traceback (most recent call last):
[...]
File "[snip]google_music/session.py", line 23, in dump_token
    with token_path.open('w') as f:
  File "/usr/lib64/python3.7/pathlib.py", line 1176, in open
    opener=self._opener)
  File "/usr/lib64/python3.7/pathlib.py", line 1030, in _opener
    return self._accessor.open(self, flags, mode)
IsADirectoryError: [Errno 21] Is a directory: '~/.local/share/google-music/musicmanager.token'
```

**Comment by thebigmunch** [comment]
Released. As always, thanks for the report. And let me know if I screwed anything else up : P
