### ISSUE TITLE
Handle requests exceptions when making a session request during upload

### ISSUE THREAD

**Issue by ScottESanDiego** [thebigmunch/google-music#9]
I'm re-uploading my library (yay, artwork!), and find that I get this error ever 6000-ish songs during an `upload`:

```
Traceback (most recent call last):
  File "/data/software/gms/bin/gms", line 10, in <module>
    sys.exit(run())
  File "/data/software/gms/lib/python3.6/site-packages/google_music_scripts/cli.py", line 920, in run
    DISPATCH[command](args)
  File "/data/software/gms/lib/python3.6/site-packages/google_music_scripts/commands.py", line 425, in do_upload
    delete_on_success=args.delete_on_success
  File "/data/software/gms/lib/python3.6/site-packages/google_music_scripts/core.py", line 320, in upload_songs
    'FAILURE'
TypeError: log() missing 1 required positional argument: '_message'
```

Re-running the same command works, but typically errors out after about the same number of songs.  I'm running with most things unlimited, but an 8k stack - maybe that's it?  I don't see excessive CPU or memory usage at runtime, and the error isn't intuitive to me.  (It points to...
```logger.log(
                                        'FAILURE'
                                        f"({filenum:>{pad}}/{total}) Failed -- {result['filepath']} | {result['reason']}"
```

...but suspect that's not the actual problem)

The command is `gms upload -v -u ScottESanDiego --album-art folder.jpg /data/media/mp3/Rock` .

**Comment by thebigmunch** [comment]
Moved to the google-music repo as that's where the code is. I'll be adding handling of exceptions from requests to the session request part of the upload process that this happens in so it will retry in those cases.
